### ISSUE TITLE
Interactive example of the 3d directional convex hull using chemiscope widget

### ISSUE THREAD

**Issue by agoscinski** [lab-cosmo/software-cookbook#1]
We made an example in scikit-matter, but since we don't want an external dependency on chemiscope for the examples, it does not fit to scikit-matter, but rather into the cookbook
https://scikit-matter.readthedocs.io/en/latest/examples/selection/GCH-ROY.html#sphx-glr-examples-selection-gch-roy-py

**Comment by ceriottm** [comment]
I think we can close this now, given that as of #27 the roy-gch example is part of the cookbook
